"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:yellow fg:surface0)\
$directory\
[](fg:yellow bg:orange)\
$git_branch\
$git_status\
[](fg:orange bg:red)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:red bg:maroon)\
$docker_context\
[ ](fg:maroon)\
$line_break$character"""

palette = 'matte_black'

[palettes.matte_black]
orange = "#d5840e"
red = "#f00000"
maroon = "#b81d1b"
yellow = "#ebb108"
text = "#cdd6f4"
surface0 = "#313244"
base = "#1e1e2e"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documentos" = "󰈙 "
"Downloads" = " "
"Músicas" = "󰝚 "
"Imagens" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:orange"
format = '[[ $symbol $branch ](fg:base bg:orange)]($style)'

[git_status]
style = "bg:orange"
format = '[[($all_status$ahead_behind )](fg:base bg:orange)]($style)'

[nodejs]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[c]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[rust]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[golang]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[php]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[java]
symbol = " "
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[kotlin]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[haskell]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[python]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $version) ](fg:base bg:red)]($style)'

[docker_context]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $context) ](fg:#83a598 bg:maroon)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:orange)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:yellow)'
vimcmd_replace_one_symbol = '[](bold fg:yellow)'
vimcmd_replace_symbol = '[](bold fg:yellow)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
